language: python
python:
    - "3"
install: 
    - python setup.py install
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - pip install coveralls
script:
    - coverage run --source=hn setup.py test
after_success:
    - coveralls
notifications:
  email: false
